version: 2
updates:
  # Python dependencies check
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
  # for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["2.x"]
      - dependency-name: "actions/setup-python"
        versions: ["2.x"]
